// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var auth, v, vh;

  auth = require('./auth/auth');

  vh = require('./validation_helpers');

  v = {};

  v.is_user = function(doc) {
    return doc._id.indexOf('org.couchdb.user:') === 0;
  };

  v.validate_doc_update = function(new_doc, old_doc, user_ctx, sec_obj) {
    var actions, new_audit_entries;
    if (!v.is_user(new_doc) || vh.is_super_admin(user_ctx)) {
      return;
    }
    new_audit_entries = v.get_new_audit_entries(new_doc, old_doc);
    if (!new_audit_entries.length) {
      return;
    }
    actions = {
      'r+': function(event, user) {
        return auth.add_resource_role(user, event.k, event.v);
      },
      'r-': function(event, user) {
        return auth.remove_resource_role(user, event.k, event.v);
      }
    };
    return vh.validate_audit_entries(actions, new_audit_entries, user_ctx, old_doc);
  };

  module.exports = v;

}).call(this);
