// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var gh;

  gh = function(auth) {
    var is_gh_team_admin;
    is_gh_team_admin = function(actor, team) {
      return auth._has_resource_role(actor, 'gh', 'user') && auth._is_team_admin(actor, team);
    };
    return auth.gh = {
      add_team_asset: function(actor, team) {
        return auth.kratos._is_kratos_admin(actor) || is_gh_team_admin(actor, team);
      },
      remove_team_asset: function(actor, team) {
        return auth.kratos._is_kratos_admin(actor) || is_gh_team_admin(actor, team);
      },
      add_resource_role: function(actor, role) {
        return auth.is_kratos_system_user(actor);
      },
      remove_resource_role: function(actor, role) {
        return auth.is_kratos_system_user(actor);
      },
      _is_gh_team_admin: is_gh_team_admin
    };
  };

  module.exports = gh;

}).call(this);
