// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var moirai;

  moirai = function(auth) {
    var is_moirai_team_admin;
    is_moirai_team_admin = function(actor, team) {
      return auth._has_resource_role(actor, 'moirai', 'user') && auth._is_team_admin(actor, team);
    };
    return auth.moirai = {
      add_team_asset: function(actor, team) {
        return auth.kratos._is_kratos_admin(actor) || is_moirai_team_admin(actor, team);
      },
      remove_team_asset: function(actor, team) {
        return auth.kratos._is_kratos_admin(actor) || is_moirai_team_admin(actor, team);
      },
      add_resource_role: function(actor, role) {
        return auth.is_kratos_system_user(actor);
      },
      remove_resource_role: function(actor, role) {
        return auth.is_kratos_system_user(actor);
      },
      _is_moirai_team_admin: is_moirai_team_admin
    };
  };

  module.exports = moirai;

}).call(this);
