// Generated by CoffeeScript 1.9.2
(function() {
  var user, users;

  users = require('./users');

  user = {};

  user.handleGetUser = function(req, resp) {
    return users.getUser(req.couch, req.session.user).pipe(resp);
  };

  module.exports = user;

}).call(this);
