// Generated by CoffeeScript 1.9.2
(function() {
  var auth,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  auth = {
    is_system_user: function(user) {
      var ref;
      return (ref = user.name) === 'admin';
    },
    is_active_user: function(user) {
      return auth.is_system_user(user) || indexOf.call(user.roles || [], 'kratos|enabled') >= 0;
    },
    _is_user: function(doc) {
      return doc._id.indexOf('org.couchdb.user:') === 0;
    }
  };

  module.exports = auth;

}).call(this);
