// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var forms;

  forms = function(validation) {
    validation.forms = {};
    return require('./user_data')(validation.forms);
  };

  module.exports = forms;

}).call(this);
