// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var auth, h;

  auth = require('./validation/index').auth;

  h = require('pantheon-helpers').design_docs.helpers;

  h.add_team_perms = function(original_team, user) {

    /*
    return a copy of the team with permissions metadata added to the roles and resources
     */
    var perms, role_name, rsrc_auth, rsrc_name, team, _i, _j, _len, _len1, _ref, _ref1;
    team = JSON.parse(JSON.stringify(original_team));
    _ref = auth.resources;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      rsrc_name = _ref[_i];
      rsrc_auth = auth[rsrc_name];
      perms = h.mk_objs(team.rsrcs, [rsrc_name, 'perms'], {
        add: rsrc_auth.add_team_asset(user, team),
        remove: rsrc_auth.remove_team_asset(user, team)
      });
    }
    _ref1 = auth.roles.team;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      role_name = _ref1[_j];
      h.mk_objs(team.roles, [role_name, 'perms'], {
        add: auth.add_team_member(user, team, role_name),
        remove: auth.remove_team_member(user, team, role_name)
      });
    }
    return team;
  };

  module.exports = h;

}).call(this);
