// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var auth, v, vh;

  auth = require('./auth/auth');

  vh = require('./validation_helpers');

  v = {};

  v.is_team = function(doc) {
    return doc._id.indexOf('team_') === 0;
  };

  v.validate_doc_update = function(new_doc, old_doc, user_ctx, sec_obj) {
    var actions, new_audit_entries;
    if (!v.is_team(new_doc) || vh.is_super_admin(user_ctx)) {
      return;
    }
    new_audit_entries = v.get_new_audit_entries(new_doc, old_doc);
    if (!new_audit_entries.length) {
      return;
    }
    actions = {
      't+': function(event, user, team) {
        return auth.kratos.add_team(user, team, event.k);
      },
      'u+': function(event, user, team) {
        return auth.kratos.add_team_member(user, team, event.k);
      },
      'u-': function(event, user, team) {
        return auth.kratos.remove_team_member(user, team, event.k);
      },
      'a+': function(event, user, team) {
        return auth.add_team_asset(user, team, event.k);
      },
      'a-': function(event, user, team) {
        return auth.remove_team_asset(user, team, event.k);
      }
    };
    return vh.validate_audit_entries(actions, new_audit_entries, user_ctx, old_doc);
  };

  module.exports = v;

}).call(this);
