// Generated by CoffeeScript 1.9.2
(function() {
  var config, config_secret, deepExtend, e, path;

  deepExtend = require('pantheon-helpers').utils.deepExtend;

  path = require('path');

  try {
    config_secret = require('./config_secret');
  } catch (_error) {
    e = _error;
    config_secret = {};
  }

  config = {
    COUCHDB: {
      HOST: 'localhost',
      PORT: 5984,
      HTTPS: false,
      SYSTEM_USER: 'admin'
    },
    RESOURCES: {
      GH: {
        ORG_ID: void 0,
        ORG_NAME: void 0,
        TEMPLATE_REPO: void 0,
        ADMIN_CREDENTIALS: {
          user: void 0,
          pass: void 0
        },
        UNMANAGED_TEAMS: [],
        UNMANAGED_REPOS: []
      },
      MOIRAI: {
        URL: 'http://localhost/moirai',
        ADMIN_CREDENTIALS: {
          user: void 0,
          pass: void 0
        }
      }
    },
    SECRET_KEY: void 0,
    COUCH_PWD: void 0,
    COUCH_DESIGN_DOCS_DIR: path.join(__dirname, '/design_docs'),
    ORGS: [],
    LOGGERS: {
      WEB: {
        streams: [
          {
            path: '/var/log/kratos/web-error.log',
            level: "error"
          }, {
            path: '/var/log/kratos/web.log',
            level: "info"
          }
        ]
      },
      WORKER: {
        streams: [
          {
            path: '/var/log/kratos/worker-error.log',
            level: "error"
          }, {
            path: '/var/log/kratos/worker.log',
            level: "info"
          }
        ]
      }
    }
  };

  deepExtend(config, config_secret);

  module.exports = config;

}).call(this);
