// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var config, config_secret, e, _deepExtend;

  _deepExtend = function(target, source) {

    /*
    recursively extend an object.
    does not recurse into arrays
     */
    var k, sv, tv;
    for (k in source) {
      sv = source[k];
      tv = target[k];
      if (tv instanceof Array) {
        target[k] = sv;
      } else if (typeof tv === 'object' && typeof sv === 'object') {
        target[k] = _deepExtend(tv, sv);
      } else {
        target[k] = sv;
      }
    }
    return target;
  };

  try {
    config_secret = require('./config_secret');
  } catch (_error) {
    e = _error;
    config_secret = {};
  }

  config = {
    COUCHDB: {
      HOST: 'localhost',
      PORT: 5984,
      HTTPS: false,
      SYSTEM_USER: 'admin'
    },
    RESOURCES: {
      GH: {
        ORG_ID: void 0,
        ORG_NAME: void 0,
        TEMPLATE_REPO: void 0,
        ADMIN_CREDENTIALS: {
          user: void 0,
          pass: void 0
        },
        UNMANAGED_TEAMS: [],
        UNMANAGED_REPOS: []
      },
      MOIRAI: {
        URL: 'http://localhost/moirai',
        ADMIN_CREDENTIALS: {
          user: void 0,
          pass: void 0
        }
      }
    },
    SECRET_KEY: void 0,
    COUCH_PWD: void 0,
    ORGS: []
  };

  _deepExtend(config, config_secret);

  module.exports = config;

}).call(this);
