// Generated by CoffeeScript 1.9.2
(function() {
  var Promise, _, conf, couch_utils;

  conf = require('./config');

  couch_utils = require('pantheon-helpers').couch_utils(conf);

  Promise = require('pantheon-helpers').promise;

  _ = require('underscore');

  couch_utils.map = function(db, fn) {
    return db.list({
      include_docs: true
    }, 'promise').then(function(docs) {
      var docs_to_save, i, j, len, new_doc, new_docs, old_doc, old_docs;
      old_docs = JSON.parse(JSON.stringify(docs.rows));
      new_docs = docs.rows.map(function(row) {
        if (row.doc._id.indexOf('_design') === 0) {
          return row.doc;
        } else {
          return fn(row.doc);
        }
      });
      docs_to_save = [];
      for (i = j = 0, len = old_docs.length; j < len; i = ++j) {
        old_doc = old_docs[i];
        new_doc = new_docs[i];
        if (!_.isEqual(old_doc, new_doc)) {
          docs_to_save.push(new_doc);
        }
      }
      if (docs_to_save.length) {
        return db.bulk({
          docs: docs_to_save
        }, 'promise');
      } else {
        return Promise.resolve('Nothing to Do');
      }
    });
  };

  couch_utils.delete_all = function(db) {
    return couch_utils.map(db, function(doc) {
      doc._deleted = true;
      return doc;
    });
  };

  module.exports = couch_utils;

}).call(this);
