// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var Promise, conf, couch_utils, _;

  conf = require('./config');

  couch_utils = require('pantheon-helpers').couch_utils(conf);

  Promise = require('pantheon-helpers').promise;

  _ = require('underscore');

  couch_utils.map = function(db, fn) {
    return db.list({
      include_docs: true
    }, 'promise').then(function(docs) {
      var docs_to_save, i, new_doc, new_docs, old_doc, old_docs, _i, _len;
      old_docs = JSON.parse(JSON.stringify(docs.rows));
      new_docs = docs.rows.map(function(row) {
        if (row.doc._id.indexOf('_design') === 0) {
          return row.doc;
        } else {
          return fn(row.doc);
        }
      });
      docs_to_save = [];
      for (i = _i = 0, _len = old_docs.length; _i < _len; i = ++_i) {
        old_doc = old_docs[i];
        new_doc = new_docs[i];
        if (!_.isEqual(old_doc, new_doc)) {
          docs_to_save.push(new_doc);
        }
      }
      if (docs_to_save.length) {
        return db.bulk({
          docs: docs_to_save
        }, 'promise');
      } else {
        return Promise.resolve('Nothing to Do');
      }
    });
  };

  couch_utils.delete_all = function(db) {
    return couch_utils.map(db, function(doc) {
      doc._deleted = true;
      return doc;
    });
  };

  module.exports = couch_utils;

}).call(this);
