// Generated by CoffeeScript 1.9.2
(function() {
  var auth, basic_auth, conf, couchUtils, middleware, utils;

  couchUtils = require('./couch_utils');

  basic_auth = require('basic-auth');

  auth = require('./validation').auth;

  conf = require('./config');

  utils = require('./utils');

  middleware = require('pantheon-helpers').middleware;

  middleware.systemAuth = middleware.systemAuth(conf);

  middleware.couch = middleware.couch(couchUtils);

  middleware.authHack = function(req, resp, next) {
    if (req.headers.cookie) {
      req.headers.cookie = req.headers.cookie.replace(/express_sess="(.*?)"/, 'express_sess=$1');
    }
    return next();
  };

  middleware.ensureActive = function(req, resp, next) {
    return utils.getActor(couchUtils, req.session.user).then(function(user) {
      if (!auth.is_active_user(user)) {
        req.session.user = null;
        return resp.status(401).end(JSON.stringify({
          error: "unauthorized",
          msg: "Account disabled. Ask administrator to re-enable."
        }));
      } else {
        return next();
      }
    }, function(err) {
      return resp.status(401).end(JSON.stringify({
        error: req.session.user,
        msg: err
      }));
    });
  };

  module.exports = middleware;

}).call(this);
