// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var auth, conf, couch_utils;

  couch_utils = require('./couch_utils');

  auth = require('basic-auth');

  conf = require('./config');

  module.exports = {
    auth_hack: function(req, resp, next) {
      if (req.headers.cookie) {
        req.headers.cookie = req.headers.cookie.replace(/express_sess="(.*?)"/, 'express_sess=$1');
      }
      return next();
    },
    couch: function(req, resp, next) {
      var credentials;
      credentials = auth(req);
      if (credentials && credentials.name === 'admin' && (credentials.pass = conf.COUCH_PWD)) {
        req.session.user = 'admin';
      }
      if (!req.session.user) {
        return resp.status(401).end(JSON.stringify({
          error: "unauthorized",
          msg: "You are not logged in."
        }));
      }
      req.couch = couch_utils.nano_user(req.session.user);
      return next();
    }
  };

}).call(this);
