// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var teams, user, users;

  teams = require('./api/teams');

  users = require('./api/users');

  user = require('./api/user');

  module.exports = function(app) {
    app.get('/kratos/orgs/:org_id/teams/', teams.handle_get_teams);
    app.get('/kratos/orgs/:org_id/teams/:team_id', teams.handle_get_team);
    app.put('/kratos/orgs/:org_id/teams/:team_id', teams.handle_create_team);
    app.put('/kratos/orgs/:org_id/teams/:team_id/roles/:key/:value/', teams.handle_add_remove_member_asset('u+'));
    app["delete"]('/kratos/orgs/:org_id/teams/:team_id/roles/:key/:value/', teams.handle_add_remove_member_asset('u-'));
    app.post('/kratos/orgs/:org_id/teams/:team_id/resources/:key/', teams.handle_add_asset);
    app["delete"]('/kratos/orgs/:org_id/teams/:team_id/resources/:key/:value/', teams.handle_add_remove_member_asset('a-'));
    app.get('/kratos/users', users.handle_get_users);
    app.post('/kratos/users', users.handle_add_user);
    app.get('/kratos/users/:user_id', users.handle_get_user);
    app.put('/kratos/users/:user_id/roles/:resource/:role', users.handle_add_remove_role('r+'));
    app["delete"]('/kratos/users/:user_id/roles/:resource/:role', users.handle_add_remove_role('r-'));
    app.put('/kratos/users/:user_id/data/:path?*', users.handle_add_data);
    return app.get('/kratos/user', user.handle_get_user);
  };

}).call(this);
