// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var audit, teams, user, users;

  teams = require('./api/teams');

  users = require('./api/users');

  user = require('./api/user');

  audit = require('./api/audit');

  module.exports = function(app) {
    app.get('/kratos/orgs/:org_id/teams/', teams.handle_get_teams);
    app.get('/kratos/orgs/:org_id/teams/:team_id', teams.handle_get_team);
    app.put('/kratos/orgs/:org_id/teams/:team_id', teams.handle_create_team);
    app.put('/kratos/orgs/:org_id/teams/:team_id/roles/:role/:user_id/', teams.handle_add_member);
    app["delete"]('/kratos/orgs/:org_id/teams/:team_id/roles/:role/:user_id/', teams.handle_remove_member);
    app.post('/kratos/orgs/:org_id/teams/:team_id/resources/:resource/', teams.handle_add_asset);
    app["delete"]('/kratos/orgs/:org_id/teams/:team_id/resources/:resource/:asset_id/', teams.handle_remove_asset);
    app.get('/kratos/users', users.handle_get_users);
    app.post('/kratos/users', users.handle_create_user);
    app.get('/kratos/users/:user_id', users.handle_get_user);
    app.put('/kratos/users/:user_id', users.handle_reactivate_user);
    app["delete"]('/kratos/users/:user_id', users.handle_deactivate_user);
    app.put('/kratos/users/:user_id/roles/:resource/:role', users.handle_add_role);
    app["delete"]('/kratos/users/:user_id/roles/:resource/:role', users.handle_remove_role);
    app.put('/kratos/users/:user_id/data/:path?*', users.handle_add_data);
    app.get('/kratos/user', user.handle_get_user);
    return app.get('/kratos/audit', audit.handleGetAudit);
  };

}).call(this);
