// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var teams, user, users;

  teams = require('./api/teams');

  users = require('./api/users');

  user = require('./api/user');

  module.exports = function(app) {
    app.get('/kratos/orgs/:org_id/teams/', teams.get_teams);
    app.get('/kratos/orgs/:org_id/teams/:team_id', teams.get_team);
    app.put('/kratos/orgs/:org_id/teams/:team_id', teams.create_team);
    app.put('/kratos/orgs/:org_id/teams/:team_id/roles/:key/:value/', teams.add_remove_member_asset('u+'));
    app["delete"]('/kratos/orgs/:org_id/teams/:team_id/roles/:key/:value/', teams.add_remove_member_asset('u-'));
    app.post('/kratos/orgs/:org_id/teams/:team_id/resources/:key/', teams.add_asset);
    app["delete"]('/kratos/orgs/:org_id/teams/:team_id/resources/:key/:value/', teams.add_remove_member_asset('a-'));
    app.get('/kratos/users', users.get_users);
    app.get('/kratos/users/:user_id', users.get_user);
    app.put('/kratos/users/:user_id/roles/:resource/:role', users.add_remove_role('r+'));
    app["delete"]('/kratos/users/:user_id/roles/:resource/:role', users.add_remove_role('r-'));
    return app.get('/kratos/user', user.get_user);
  };

}).call(this);
