// Generated by CoffeeScript 1.9.2
(function() {
  var _, api, conf, couchUtils, db, follow, getPlugins, handlers, i, len, logger, org, orgs, plugins, validation, worker;

  worker = require('pantheon-helpers').worker;

  _ = require('underscore');

  follow = require('follow');

  couchUtils = require('./couch_utils');

  conf = require('./config');

  validation = require('./validation');

  logger = require('./loggers').worker;

  api = require('./api');

  getPlugins = require('../utils').getPlugins;

  plugins = getPlugins();

  handlers = plugins.map(function(plugin) {
    return {
      name: plugin.name,
      workers: plugin.workers(api, validation, couchUtils)
    };
  });

  orgs = conf.ORGS;

  for (i = 0, len = orgs.length; i < len; i++) {
    org = orgs[i];
    db = couchUtils.nano_system_user.use('org_' + org);
    worker.start_worker(logger, db, handlers, validation._get_doc_type, worker.getPluginHandlers);
  }

  db = couchUtils.nano_system_user.use('_users');

  worker.start_worker(logger, db, handlers, validation._get_doc_type, worker.getPluginHandlers);

}).call(this);
