// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var x;

  x = {};

  x.get_handlers = function(entry, db_type, resources) {

    /*
    return a hash of only the handlers that should be called for this entry
    and db_type
     */
    var filtered_handlers, handler, handlers, resource, _ref, _ref1, _ref2, _ref3, _ref4;
    filtered_handlers = {};
    for (resource in resources) {
      handlers = resources[resource];
      handler = (_ref = handlers[db_type]) != null ? _ref[entry.a] : void 0;
      if (!handler) {
        if (entry.k === resource) {
          handler = (_ref1 = handlers[db_type]) != null ? (_ref2 = _ref1.self) != null ? _ref2[entry.a] : void 0 : void 0;
        } else {
          handler = (_ref3 = handlers[db_type]) != null ? (_ref4 = _ref3.other) != null ? _ref4[entry.a] : void 0 : void 0;
        }
      }
      if (handler) {
        filtered_handlers[resource] = handler;
      }
    }
    return filtered_handlers;
  };

  module.exports = x;

}).call(this);
