// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var conf, couch_utils, db, follow, get_handler_data_path, handlers, org, orgs, validate, worker, _, _i, _len;

  worker = require('pantheon-helpers/lib/worker');

  _ = require('underscore');

  follow = require('follow');

  couch_utils = require('./couch_utils');

  conf = require('./config');

  validate = require('./validation/validate');

  orgs = conf.ORGS;

  handlers = {
    gh: require('./workers/gh').handlers
  };

  get_handler_data_path = function(doc_type, rsrc) {
    return {
      'user': ['rsrcs', rsrc],
      'team': ['rsrcs', rsrc, 'data']
    }[doc_type];
  };

  for (_i = 0, _len = orgs.length; _i < _len; _i++) {
    org = orgs[_i];
    db = couch_utils.nano_admin.use('org_' + org);
    worker.start_worker(db, handlers, get_handler_data_path, validate._get_doc_type);
  }

  db = couch_utils.nano_admin.use('_users');

  worker.start_worker(db, handlers, get_handler_data_path, validate._get_doc_type);

}).call(this);
