// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var conf, couch_utils, db, follow, handlers, logger, org, orgs, validate, worker, _, _i, _len;

  worker = require('pantheon-helpers').worker;

  _ = require('underscore');

  follow = require('follow');

  couch_utils = require('./couch_utils');

  conf = require('./config');

  validate = require('./validation');

  logger = require('./loggers').worker;

  orgs = conf.ORGS;

  handlers = {
    gh: require('./workers/gh').handlers,
    moirai: require('./workers/moirai').handlers
  };

  for (_i = 0, _len = orgs.length; _i < _len; _i++) {
    org = orgs[_i];
    db = couch_utils.nano_system_user.use('org_' + org);
    worker.start_worker(logger, db, handlers, validate._get_doc_type, worker.get_plugin_handlers);
  }

  db = couch_utils.nano_system_user.use('_users');

  worker.start_worker(logger, db, handlers, validate._get_doc_type, worker.get_plugin_handlers);

}).call(this);
