// Generated by CoffeeScript 1.9.2
(function() {
  var schema;

  schema = function(validation) {
    validation.schema = {};
    return require('./user_data')(validation.schema);
  };

  module.exports = schema;

}).call(this);
