// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var PubKeyField, fields, user_data,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  fields = require('validoc').fields;

  PubKeyField = (function(_super) {
    __extends(PubKeyField, _super);

    function PubKeyField() {
      return PubKeyField.__super__.constructor.apply(this, arguments);
    }


    /*
    A field that contains a valid public key.
     */

    PubKeyField.prototype.regex = /^ssh-rsa AAAA[0-9A-Za-z+/]+[=]{0,3} [0-9A-Za-z.-]+(@[0-9A-Za-z.-]+)?$/;

    PubKeyField.prototype.errorMessage = "invalid public key";

    return PubKeyField;

  })(fields.RegexField);

  fields.PubKeyField = PubKeyField;

  user_data = function(schema) {
    var pubKeyField, pubKeyListField, selfSchema, systemSchema;
    pubKeyField = {
      name: 'publicKey',
      field: 'ContainerField',
      schema: [
        {
          name: 'name',
          field: 'CharField',
          maxLength: 20
        }, {
          name: 'key',
          field: 'PubKeyField'
        }
      ]
    };
    pubKeyListField = {
      name: 'publicKeys',
      field: 'ListField',
      schema: pubKeyField,
      required: false
    };
    systemSchema = {
      name: 'systemFields',
      field: 'ContainerField',
      schema: [
        {
          name: 'contractor',
          field: 'NullBooleanField'
        }, {
          name: 'username',
          field: 'CharField',
          maxLength: 40
        }, pubKeyListField
      ]
    };
    selfSchema = {
      name: 'systemFields',
      field: 'ContainerField',
      schema: [pubKeyListField]
    };
    return schema.user_data = {
      self: function(opts) {
        return fields.genField(selfSchema, opts);
      },
      system: function(opts) {
        return fields.genField(systemSchema, opts);
      }
    };
  };

  module.exports = user_data;

}).call(this);
