// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var fields, user_data;

  fields = require('validoc').fields;

  user_data = function(schema) {
    var pubKeyField, pubKeyListField, selfSchema, systemSchema;
    pubKeyField = {
      name: 'publicKey',
      field: 'ContainerField',
      schema: [
        {
          name: 'name',
          field: 'CharField',
          maxLength: 20
        }, {
          name: 'key',
          field: 'CharField',
          maxLength: 500
        }
      ]
    };
    pubKeyListField = {
      name: 'publicKeys',
      field: 'ListField',
      schema: pubKeyField,
      required: false
    };
    systemSchema = {
      name: 'systemFields',
      field: 'ContainerField',
      schema: [
        {
          name: 'contractor',
          field: 'NullBooleanField'
        }, {
          name: 'username',
          field: 'CharField',
          maxLength: 40
        }, pubKeyListField
      ]
    };
    selfSchema = {
      name: 'systemFields',
      field: 'ContainerField',
      schema: [pubKeyListField]
    };
    return schema.user_data = {
      self: function(opts) {
        return fields.genField(selfSchema, opts);
      },
      system: function(opts) {
        return fields.genField(systemSchema, opts);
      }
    };
  };

  module.exports = user_data;

}).call(this);
