// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(validation) {
    return {
      add_resource_role: function(actor, role) {
        return validation.auth.is_kratos_system_user(actor);
      },
      remove_resource_role: function(actor, role) {
        return validation.auth.is_kratos_system_user(actor);
      },
      _is_kratos_admin: function(actor) {
        return validation.auth._is_resource_admin(actor, 'kratos');
      }
    };
  };

}).call(this);
