// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var gh;

  gh = function(validation) {
    return validation.gh = {
      add_team_asset: function(team, asset) {},
      remove_team_asset: function(team, asset) {}
    };
  };

  module.exports = gh;

}).call(this);
