// Generated by IcedCoffeeScript 1.8.0-c
(function() {
  var moirai;

  moirai = function(validation) {
    return validation.moirai = {
      add_team_asset: function(team, asset) {},
      remove_team_asset: function(team, asset) {}
    };
  };

  module.exports = moirai;

}).call(this);
