_ = require('underscore')
s = require('underscore.string')
Promise = require('pantheon-helpers').promise
utils = require('pantheon-helpers').utils

utils.getOrgDbs = () ->
  ###
  return promise only
  return all organization databases
  ###
  couchUtils = require('./couch_utils')
  couchUtils.nano_system_user.db.list('promise').then((dbs) ->
    out = _.filter(dbs, (x) -> x.indexOf('org_') == 0)
    Promise.resolve(out)
  )

utils.getPluginImportStrings = () ->
  ###
  return the import string for all plugins
  gets plugin names from conf.resources keys.
  import string can be explicitly defined via config.resource.RESOURCE_NAME.REQUIRE_NAME string
  or it can be autogenerated config.resource.RESOURCE_NAME.
  ###
  conf = require('./config')

  pluginNames = _.map(conf.RESOURCES, (plugin, pluginName) ->
    if plugin.REQUIRE_NAME?
      return plugin.REQUIRE_NAME
    else
      return 'kratos-' + pluginName.toLowerCase()
  )
  return pluginNames

utils.getPlugins = () ->
  pluginNames = utils.getPluginImportStrings()
  plugins = pluginNames.map((pluginName) ->
    return require(pluginName)
  )

module.exports = utils
