// Generated by CoffeeScript 1.9.2
(function() {
  var auth;

  auth = {
    _is_team: function(doc) {
      return doc._id.indexOf('team_') === 0;
    }
  };

  module.exports = auth;

}).call(this);
